---
- name: ANSISTRANO | Unarchive | Unarchive source
  unarchive:
    copy: no
    owner: "{{ ansistrano_unarchive_owner }}"
    group: "{{ ansistrano_unarchive_group }}"
    src: "{{ ansistrano_archived_file }}"
    dest: "{{ ansistrano_release_path.stdout }}"

- name: ANSISTRANO | Unarchive | Delete archived file
  file:
    path: "{{ ansistrano_archived_file }}"
    state: absent